spring:
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: group-2
app:
  kafka_topics:
    order-topic: "order-topic"
    order-status-topic: "order-status-topic"
server:
  port: 8081
